version: "3.9"
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
